# Generated by Django 2.2 on 2021-04-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210407_0218'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_constraint',
        ),
    ]
